---
# We will evaluate each summary against the appropriate set of devices for that
# area. The device name will match the device and we will exercise the restorable
# attributes for the device from  the synthetic home custom component.
area_configs:
  - area: Kitchen
    instructions:
      - Check if the Kitchen Light is currently turned on
      - Determine if the Refrigerator is running efficiently
  - area: Living Room
    instructions:
      - Verify if the Living Room Light is set to an appropriate brightness
      - See if the Smart Speaker is connected and ready to use
  - area: Game Room
    instructions:
      - Check if the Game Room Light is functioning properly
      - Check the status of the Game Console for any updates
  - area: Backyard
    instructions:
      - Ensure that the Deck Lights in the Backyard are operational
      - Verify if the Outdoor Camera in the Backyard is detecting motion accurately
  - area: Garage
    instructions:
      - Check if the Garage Door Opener is closed or opened
      - Verify the status of the Toolbox Sensor in the Garage
  - area: Bedroom 1
    instructions:
      - Determine if the Bedroom 1 Light is on or off
      - Check if the Smart Lock in Bedroom 1 is locked properly
  - area: Bedroom 2
    instructions:
      - Verify the status of the Bedroom 2 Light for proper illumination
      - Check the Climate Sensor in Bedroom 2 for accurate temperature readings
  - area: Bedroom 3
    instructions:
      - Ensure that the Bedroom 3 Light is functioning correctly
      - Verify if the Window Sensor in Bedroom 3 is detecting any open windows
  - area: Master Bedroom
    instructions:
      - Check the brightness level of the Master Bedroom Light
      - Ensure that the Sleep Tracker in the Master Bedroom is providing accurate data
